language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t kuantse/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kuantse/docker-react npm run test
